// MIMESIS Patches - MelonLoader entry point, compiled into every patch
// Author: Mohamed Darwesh (@medovanx) - https://github.com/medovanx
//
// The game files stay untouched: <Patch>.Plugin.Init() runs from a Harmony prefix on Hub.Awake, when the game's
// managers exist, and sets up the patch's Harmony patches and its page in the Patches window.
// The mod's name, version and author come from the MelonInfo attribute generated by Directory.Build.targets.

using System;
using HarmonyLib;
using MelonLoader;

namespace MimesisPatches
{
    public sealed class MelonEntry : MelonMod
    {
        static Action _init;

        public override void OnInitializeMelon()
        {
            var plugin = typeof(MelonEntry).Assembly.GetType(Info.Name + ".Plugin");
            var init = plugin?.GetMethod("Init", Type.EmptyTypes);
            if (init == null) { LoggerInstance.Error($"{Info.Name}.Plugin.Init not found"); return; }
            _init = (Action)Delegate.CreateDelegate(typeof(Action), init);
            HarmonyInstance.Patch(AccessTools.Method(typeof(Hub), "Awake"), prefix: new HarmonyMethod(typeof(MelonEntry), nameof(HubAwake)));
            LoggerInstance.Msg($"{Info.Name} {Info.Version} loaded; starts with the game");
        }

        static void HubAwake() => _init?.Invoke();
    }
}
